# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Stan Baek
author: Stan Baek 
logo: stanbaek.png
copyright: '2024' # Copyright year to be placed in the footer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
#######################################################################################
# Execution settings
# execute:
#   execute_notebooks: off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
#   allow_errors: true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.

# Define the name of the latex output file for PDF builds
# latex:
#   latex_engine: pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
#   latex_documents:
#     targetname: ece487.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#  - references.bib

jb:
  version: 0.15.2

toc:
  include: ["index"]
# Information about where the book exists on the web
repository:
  url: https://github.com/stanbaek/stanbaek.github.io # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  #branch: master  # Which branch of the repository should be used when creating links (optional)

output_dir: "docs"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# html:
#   favicon: favicon.ico
#   use_issues_button: true
#   use_repository_button: true

# output: 
#   html_document:
#     number_sections: true
   
parse:
  myst_substitutions:
      sub3: My _global_ value!
  myst_enable_extensions:
    # for parsing of dollar $ and $$ encapsulated math.
    - dollarmath
    #  for direct parsing of amsmath LaTeX environments.
    - amsmath
    # To auto-detect HTML-like links in your markdown and convert them to hyperlinks.
    - linkify
    # To allow you to define markdown “variables” and substitute text in using them. See Substitutions and variables in markdown.
    - substitution
    # To allow you to use ::: fences for admonitions, in order to make them easier to render in interfaces that do not support MyST. See Markdown-friendly directives with :::.
    - colon_fence
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
    - deflist
    - html_admonition
    - linkify
    - replacements
    - smartquotes
    - substitution

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions:   # A list of extra extensions to load by Sphinx.
  - sphinx_inline_tabs
  config:   # key-value pairs to directly over-ride the Sphinx configuration
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Add a "Launch on Google Colab" button to .ipynb files
# launch_buttons:
#   colab_url: "https://colab.research.google.com"